import { getDb } from "../backend/db/sqlite";

type SeedConfig = {
  products: number;
  customers: number;
  suppliers: number;
  includeLowStock: boolean;
};

const DEFAULTS: SeedConfig = {
  products: 5000,
  customers: 500,
  suppliers: 120,
  includeLowStock: true,
};

function parseArgs(argv: string[]): SeedConfig {
  const config: SeedConfig = { ...DEFAULTS };

  for (const arg of argv) {
    if (arg.startsWith("--products=")) {
      const value = Number(arg.split("=")[1]);
      if (Number.isFinite(value) && value >= 0) {
        config.products = Math.floor(value);
      }
      continue;
    }
    if (arg.startsWith("--customers=")) {
      const value = Number(arg.split("=")[1]);
      if (Number.isFinite(value) && value >= 0) {
        config.customers = Math.floor(value);
      }
      continue;
    }
    if (arg.startsWith("--suppliers=")) {
      const value = Number(arg.split("=")[1]);
      if (Number.isFinite(value) && value >= 0) {
        config.suppliers = Math.floor(value);
      }
      continue;
    }
    if (arg === "--no-low-stock") {
      config.includeLowStock = false;
    }
  }

  return config;
}

function pickCategory(index: number): string {
  const categories = ["Beverages", "Snacks", "Household", "Dairy", "Frozen", "Bakery", "Personal Care", "Stationery"];
  return categories[index % categories.length];
}

function makeProductName(index: number): string {
  const brands = ["Nimbus", "Orchid", "Terra", "Pulse", "Lumen", "Metro", "Crest", "Harbor", "Valley", "Quartz"];
  const nouns = ["Tea", "Soap", "Biscuits", "Rice", "Juice", "Powder", "Oil", "Noodles", "Cookies", "Tissue"];
  const sizes = ["100g", "250g", "500g", "750ml", "1L", "2L", "Pack", "Family Pack"];
  const brand = brands[index % brands.length];
  const noun = nouns[Math.floor(index / brands.length) % nouns.length];
  const size = sizes[Math.floor(index / (brands.length * nouns.length)) % sizes.length];
  return `${brand} ${noun} ${size}`;
}

function main() {
  const config = parseArgs(process.argv.slice(2));
  const db = getDb();

  const start = Date.now();

  const deleteSeedProducts = db.prepare("DELETE FROM products WHERE barcode_id LIKE 'SEED-%'");
  const insertProduct = db.prepare(
    `
    INSERT INTO products (
      barcode_id,
      name,
      buy_price,
      sell_price,
      stock,
      min_stock,
      default_discount_pct,
      card_surcharge_enabled,
      card_surcharge_pct
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    `,
  );

  const deleteSeedCustomers = db.prepare("DELETE FROM customers WHERE name LIKE 'Seed Customer %'");
  const insertCustomer = db.prepare("INSERT INTO customers (name, contact, total_outstanding) VALUES (?, ?, ?)");

  const deleteSeedSuppliers = db.prepare("DELETE FROM suppliers WHERE name LIKE 'Seed Supplier %'");
  const insertSupplier = db.prepare(
    "INSERT INTO suppliers (name, contact, opening_balance, total_outstanding, notes) VALUES (?, ?, ?, ?, ?)",
  );

  const runSeed = db.transaction(() => {
    deleteSeedProducts.run();
    deleteSeedCustomers.run();
    deleteSeedSuppliers.run();

    for (let i = 1; i <= config.products; i += 1) {
      const barcode = `SEED-${String(i).padStart(6, "0")}`;
      const category = pickCategory(i);
      const name = `${makeProductName(i)} ${category}`;
      const buyPrice = Number((20 + (i % 400) * 0.73).toFixed(2));
      const margin = 1.15 + ((i % 9) * 0.03);
      const sellPrice = Number((buyPrice * margin).toFixed(2));

      let stock = 6 + (i % 120);
      if (config.includeLowStock && i % 17 === 0) {
        stock = i % 6;
      }
      if (config.includeLowStock && i % 53 === 0) {
        stock = 0;
      }

      const minStock = 5;
      const discount = i % 5 === 0 ? 5 : i % 13 === 0 ? 10 : 0;
      const surchargeEnabled = i % 8 === 0 ? 1 : 0;
      const surchargePct = surchargeEnabled ? 1.5 : 0;

      insertProduct.run(
        barcode,
        name,
        buyPrice,
        sellPrice,
        stock,
        minStock,
        discount,
        surchargeEnabled,
        surchargePct,
      );
    }

    for (let i = 1; i <= config.customers; i += 1) {
      const name = `Seed Customer ${String(i).padStart(4, "0")}`;
      const contact = `0700${String(i).padStart(6, "0")}`;
      const outstanding = i % 7 === 0 ? Number((10 + (i % 200) * 0.6).toFixed(2)) : 0;
      insertCustomer.run(name, contact, outstanding);
    }

    for (let i = 1; i <= config.suppliers; i += 1) {
      const name = `Seed Supplier ${String(i).padStart(4, "0")}`;
      const contact = `0777${String(i).padStart(6, "0")}`;
      const openingBalance = Number((i % 9 === 0 ? 50 + (i % 300) : 0).toFixed(2));
      insertSupplier.run(name, contact, openingBalance, openingBalance, "Generated by seed script");
    }
  });

  runSeed();

  const elapsedMs = Date.now() - start;
  console.log("SEED_DONE");
  console.log(`products=${config.products}`);
  console.log(`customers=${config.customers}`);
  console.log(`suppliers=${config.suppliers}`);
  console.log(`db=${process.env.POS_DB_PATH || "default backend/db/pos.db"}`);
  console.log(`elapsed_ms=${elapsedMs}`);
}

main();